#!/usr/bin/env bash

set -e

url="https://charts.mikamai.com/karavel-edge"
bucket="s3://mikamai-charts-repo/karavel-edge"

echo "Releasing all edge components"
echo ""

dist="dist/karavel-edge"
rm -rf "$dist" && mkdir -p "$dist"

aws s3 cp "$bucket/index.yaml" "$dist/index.yaml" || true

helm package components/* -d "$dist"
helm repo index "$dist" --merge "$dist/index.yaml" --url "$url"

aws s3 sync "$dist" "$bucket"
